baseURL = "https://stjohnswalton.co.uk/"
languageCode = "en-us"
title = "St John's Church, Walton, Chesterfield"
theme = "sjw"
relativeURLS = true
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "St John's Church Walton {year}."

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]


[module]
    [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"


[params]
  test = 10
  pre = "<h3>Active"
  post = "</h3>"
