baseURL = "https://michealbrooker.com/"
languageCode = "en-us"
title = "Mike Brooker online"
theme = "midday"
relativeURLS = true
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
copyright = "Copyright 2000-{year} michaelbrooker.com All rights reserved."

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  expiryDate = ["expiryDate"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]

  

[module]
    [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

# Main menu - section

# The menu was removed from this config.toml file and the old one save to the
# root of this hugo site as config.toml.old
